fetchai/asi-alliance-wallet

packages/extension/src/config.ts
- adds chain config for Capricorn network
=> chore: add capricorn config (ECO-1072)

packages/extension/src/config.ts
- Add staking url to capricorn config
- Add staking url to mainnet config
| W/o balance / rewards | W/ balance / rewards |
| --- | --- |
| ![keplr-staking-no-balance](https://user-images.githubusercontent.com/600733/158867268-628c0789-fed1-4afd-815e-030ea1a77ab7.png) | ![keplr-staking](https://user-images.githubusercontent.com/600733/158867295-c75960f3-f402-4db7-a67d-80ebf190f36f.png) |
=> chore: config add staking url (ECO-1101)

packages/stores/src/account/cosmos.ts
- increase gas limits by ~20% across the board to account for recent changes in gas calculations post-upgrade
=> chore: update gas limits (ECO-1306)

packages/extension/src/manifest.json
- Update The `Manifest.json` file to change the name of the wallet extension on the chrome store. 
- Update name would be: **Fetch Wallet**
=> Update manifest.json file

README.md, package.json, packages/extension/src/index.html
**UPDATE WALLET NAME ON:**
- Package.json file 
- README.md file 
- Index.html file
=> Update wallet name on Readme.md and package.json file

docs/account_management.md, docs/address_book.md, docs/connections.md, docs/deposit.md, docs/send_tokens.md, mkdocs.yml
This PR fixes URLs of the images to remove MkDocs warnings
=> Fix image urls

packages/extension/src/manifest.json
- moves the first line from the chrome store description into the manifest.json description
=> chore: update manifest description

packages/extension/src/pages/main/tx-button.module.scss, packages/extension/src/pages/main/tx-button.tsx, packages/extension/src/pages/setting/index.tsx, packages/extension/src/pages/sign/style.module.scss
Fix : UI Fixes
Below is the list of Issues fixed.Attaching Screenshots
1. Gas price input field getting overlapped with reject button (Fixed)
2. Approve and reject button not getting displayed (Fixed)
3. "Show advanced IBC transfers" toggle (Fixed)
4. When user change the language then buttons UI not displayed properly (Fixed)
5. Space between fee value and reject button should be consistent (Fixed)
=> Fix : UI Fixes

packages/extension/src/components/form/memo-input.tsx, packages/extension/src/pages/main/tx-button.tsx, packages/extension/src/pages/more/index.tsx
Below issues are fixed.Attaching screenshot of fixes
1. Memo input field not getting displayed properly
2. Logo getting changed on IBC transfer page
=> fix UI issues

packages/extension/src/components/chatMessage/style.module.scss, packages/extension/src/layouts/header-layout/style.module.scss, packages/extension/src/pages/chat/index.tsx, packages/extension/src/pages/chat/style.module.scss, packages/extension/src/pages/chat/users.tsx, packages/extension/src/pages/chatSection/index.tsx, packages/extension/src/pages/chatSection/style.module.scss
UI fixes for fetch-wallet chat
=> UI fixes for fetch-wallet chat

packages/extension/src/components/form/address-input.tsx, packages/extension/src/config.ui.var.ts, packages/extension/src/graphQL/client.ts, packages/extension/src/graphQL/messages-api.ts, packages/extension/src/pages/chat/AuthPopup.tsx, packages/extension/src/pages/chat/index.tsx, packages/extension/src/pages/chat/users.tsx, packages/extension/src/pages/main/asset.tsx, packages/extension/src/pages/newchat/NewChat.tsx, packages/extension/src/pages/setting/address-book/add-address-modal.tsx, packages/extension/src/pages/setting/address-book/index.tsx
Merged chatui changes
1. Fixed auto-fill address issue.
2. Pick mnemonics of selected account dynamically.
3. Implemented search on chat history page .
4. Implemented search on Add new user page .
5. dynamic access token integration.
6. Flickering issue on home page
=> merged chatui changes

.eslintrc.js, packages/background/src/keyring/keyring.ts, packages/extension/src/components/form/memo-input.tsx, packages/extension/src/pages/main/account.tsx, packages/extension/src/pages/main/asset.tsx, packages/extension/src/pages/main/deposit.tsx, packages/extension/src/pages/more/index.tsx, packages/extension/src/pages/setting/export-to-mobile/index.tsx, packages/extension/src/pages/sign/index.tsx, packages/extension/src/pages/sign/messages.tsx, packages/extension/webpack.config.js, packages/stores/src/account/base.spec.ts, packages/wc-client/src/index.ts
Fixing the lints issue that are on the `master`
=> chore: fix master liniting issues

packages/extension/src/components/chat/chat-search-input.tsx, packages/extension/src/components/chat/style.module.scss, packages/extension/src/pages/chatSection/chats-view-section.tsx, packages/extension/src/pages/ibc-transfer/style.module.scss, packages/extension/src/pages/newchat/style.module.scss, packages/extension/src/pages/send/style.module.scss, packages/extension/src/pages/setting/page-button.module.scss, packages/extension/src/pages/setting/page-button.tsx
1. Added ellipsis in memo text
2. Add bottom spacing in Send button
3. Remove drag property from icons
=> fix: UI bugs and enhancement

packages/extension/src/components/chat/store.tsx, packages/extension/src/components/notification-messages/notification-item/index.tsx, packages/extension/src/components/notification-modal/index.tsx, packages/extension/src/config.ui.var.ts
change log:
Follow all org and topics by default for new users instead of fetch.ai.
Removed Get started screen when no org is followed
=> chore: followed all org and topics by default

packages/extension/package.json, packages/extension/src/config.ui.ts, packages/extension/src/config.ui.var.ts, packages/extension/src/languages/en.json, packages/extension/src/pages/register/auth/cosmos-rpc.ts, packages/extension/src/pages/register/auth/image.tsx, packages/extension/src/pages/register/auth/index.tsx, packages/extension/src/pages/register/auth/style.module.scss, packages/extension/src/pages/register/index.tsx, packages/extension/src/pages/register/mnemonic/recover-mnemonic.tsx, packages/extension/webpack.config.js, packages/hooks/src/register/index.tsx, yarn.lock
1. Create/Import an account using Google sign-in.
2. Added email label in the account list.
=> feat: Google Auth support

packages/fetch-extension/src/languages/en.json, packages/fetch-extension/src/pages/main/asset.tsx, packages/fetch-extension/src/pages/main/deposit.tsx, packages/fetch-extension/src/pages/setting/index.tsx
**Change Log:**
Temporarily hide buy button
Show export mobile option
=> show export mobile option and hide buy button

packages/fetch-extension/src/components/confirm/dialog.tsx, packages/fetch-extension/src/components/confirm/index.tsx, packages/fetch-extension/src/languages/en.json, packages/fetch-extension/src/pages/setting/export-to-mobile/index.tsx
**Change log:**
Fix export to mobile QR code issue
=> fix: export to mobile qr code data issue

packages/background/src/ledger/service.ts, packages/fetch-extension/src/layouts-v2/bottom-nav/index.tsx, packages/fetch-extension/src/new-layouts/bottom-nav/index.tsx
=> fix: ledger fixes

packages/fetch-extension/src/components-v2/dropdown/style.module.scss, packages/fetch-extension/src/components-v2/form/coin-input.module.scss, packages/fetch-extension/src/components-v2/form/coin-input.tsx, packages/fetch-extension/src/layouts-v2/bottom-nav/tab.tsx, packages/fetch-extension/src/layouts-v2/header-layout/style.module.scss, packages/fetch-extension/src/pages-new/activity/filter/index.tsx, packages/fetch-extension/src/pages-new/activity/native/index.tsx, packages/fetch-extension/src/pages-new/keyring-dev/delete/index.tsx, packages/fetch-extension/src/pages-new/lock/index.tsx, packages/fetch-extension/src/pages-new/more/index.tsx, packages/fetch-extension/src/pages-new/register/advanced-bip44.tsx, packages/fetch-extension/src/pages-new/register/mnemonic/new-mnemonic.tsx, packages/fetch-extension/src/pages-new/register/mnemonic/recover-mnemonic.module.scss, packages/fetch-extension/src/pages-new/register/mnemonic/recover-mnemonic.tsx
=> Firefox UI fixes

packages/mobile/src/stores/root.tsx
=> Mobile: custom nonce support

packages/background/package.json, packages/fetch-extension/package.json, packages/provider/package.json, yarn.lock
wallet types version updates in other packages
=> fix: wallet types version in other packages

packages/fetch-extension/package.json, packages/fetch-extension/src/index.tsx, packages/fetch-extension/src/pages-new/main/balances/index.tsx, packages/fetch-extension/src/pages-new/more/proposals/index.tsx, packages/fetch-extension/src/pages/setting/addEvmChain/index.tsx, packages/fetch-extension/src/pages/setting/addEvmChain/style.module.scss, yarn.lock
=> Extension UI fixes

packages/fetch-extension/src/pages-new/main/ledger-app-modal/index.tsx
=> Ledger fix

packages/fetch-extension/src/components-v2/form/coin-input.tsx, packages/fetch-extension/src/pages-new/asset-view/index.tsx, packages/fetch-extension/src/utils/format.ts, packages/mobile/src/components/new/asset-card-model/asset-card-model.tsx, packages/mobile/src/screens/portfolio/token-detail/token-balance-section.tsx
Update assets balance and time update on vesting info
=> Vesting enhancement

packages/fetch-extension/src/components-v2/form/coin-input.tsx, packages/fetch-extension/src/components-v2/form/fee-buttons-v2/fee-buttons.tsx, packages/fetch-extension/src/layouts-v2/header-layout/style.module.scss, packages/fetch-extension/src/pages-new/activity/activity-details/style.module.scss, packages/fetch-extension/src/pages-new/bridge/fetchhub-bridge.tsx, packages/fetch-extension/src/pages-new/main/ledger-app-modal/ledger-app-modal.module.scss, packages/fetch-extension/src/pages-new/more/ibc-transfer/index.tsx, packages/fetch-extension/src/pages-new/more/security-privacy/autolock/index.tsx, packages/fetch-extension/src/pages-new/more/security-privacy/index.tsx, packages/fetch-extension/src/pages-new/send/send-phase-1.tsx, packages/fetch-extension/src/pages-new/send/send-phase-2.tsx, packages/fetch-extension/src/pages-new/validator/delegate/index.tsx, packages/fetch-extension/src/pages-new/validator/redelegate/index.tsx, packages/fetch-extension/src/pages-new/validator/unstake/index.tsx, packages/fetch-extension/src/pages/ledger/style.module.scss
=> Send UI fixes

packages/background/src/keyring/keyring.ts
=> fix: key ring not loaded issue

packages/fetch-extension/src/components/confirm/dialog.tsx, packages/fetch-extension/src/components/confirm/index.tsx, packages/fetch-extension/src/components/confirm/style.module.scss, packages/fetch-extension/src/layouts-v2/header/chain-list.tsx, packages/fetch-extension/src/pages-new/more/manage-networks/style.module.scss, packages/fetch-extension/src/pages-new/more/view-mnemonic-seed/style.module.scss, packages/fetch-extension/src/pages-new/register/mnemonic/new-mnemonic.tsx, packages/fetch-extension/src/pages-new/register/mnemonic/recover-mnemonic.tsx
=> Chainlist UI fix

packages/fetch-extension/src/pages-new/send/send-phase-1.tsx, packages/fetch-extension/src/utils/format.ts
=> fix: Resolved an issue where the max function would crash if the value contained a comma.

packages/fetch-extension/src/languages/en.json
=> chore: Asi rebranding

packages/background/src/keyring/keyring.ts, packages/fetch-extension/src/components-v2/form/coin-input.tsx, packages/fetch-extension/src/components-v2/form/stake-input.tsx, packages/fetch-extension/src/pages-new/send/send-phase-2.tsx, packages/fetch-extension/src/utils/format.ts
=> Send page amount fix

packages/fetch-extension/src/pages-new/axelar-bridge/axelar-bridge-evm/send-token.tsx, packages/fetch-extension/src/pages-new/bridge/ethereum-bridge.tsx, packages/fetch-extension/src/pages-new/bridge/fetchhub-bridge.tsx, packages/fetch-extension/src/pages-new/more/ibc-transfer/index.tsx, packages/fetch-extension/src/pages-new/more/proposals/proposal-details/vote-dropdown.tsx, packages/fetch-extension/src/pages-new/portfolio/stats/index.tsx, packages/fetch-extension/src/pages-new/send/index.tsx, packages/fetch-extension/src/pages-new/send/send-phase-2.tsx, packages/fetch-extension/src/pages-new/stake/dashboard/my-stake/my-stakes.tsx, packages/fetch-extension/src/pages-new/validator/delegate/index.tsx, packages/fetch-extension/src/pages-new/validator/redelegate/index.tsx, packages/fetch-extension/src/pages-new/validator/unstake/index.tsx, packages/fetch-extension/src/pages-new/validator/validator-detail/stake-details/stake-details.tsx, packages/fetch-extension/src/pages/authz/index.tsx, packages/fetch-extension/src/pages/ledger/grant.tsx, packages/fetch-extension/src/pages/main/tx-button.tsx, packages/fetch-extension/src/utils/index.ts, packages/stores/src/core/interaction/ledger.ts
=> fix: Re-signing when the Ledger device is disconnected.

packages/fetch-extension/src/config.ui.ts, packages/fetch-extension/src/pages-new/main/balances/index.tsx, packages/mobile/android/app/build.gradle, packages/mobile/ios/mobile.xcodeproj/project.pbxproj, packages/mobile/src/screens/home/account-section.tsx, packages/mobile/src/screens/stake/dashboard/stake-card.tsx, packages/mobile/src/stores/root.tsx, packages/types/src/currency.ts, packages/unit/src/price-pretty.spec.ts
=> Graph currency improvement and bump android/ios 1.0.5 (25)

messaging.md
Corrected a typo:
- Replaced `succesfully` with `successfully` in the messaging instructions.
---
This PR is ready for review. 🚀
=> typo fix messaging.md

packages/fetch-extension/src/pages-new/asset-view/index.tsx, packages/fetch-extension/src/pages-new/main/balances/index.tsx, packages/fetch-extension/src/pages-new/portfolio/stats/index.tsx, packages/fetch-extension/src/pages-new/stake/dashboard/index.tsx, packages/mobile/src/components/new/staking/portfolio-staking-card.tsx, packages/mobile/src/screens/home/account-section.tsx, packages/mobile/src/screens/portfolio/native-tokens-section.tsx, packages/mobile/src/screens/portfolio/token-detail/index.tsx, packages/mobile/src/screens/portfolio/token-detail/token-balance-section.tsx, packages/mobile/src/screens/portfolio/token-detail/token-graph-section.tsx, packages/mobile/src/screens/portfolio/tokens-section.tsx, packages/mobile/src/screens/send/send-phase-1.tsx, packages/mobile/src/screens/send/send-phase-2.tsx, packages/mobile/src/screens/stake/dashboard/delegations-card.tsx, packages/mobile/src/screens/stake/dashboard/reward-card.tsx, packages/mobile/src/screens/stake/delegate/index.tsx, packages/mobile/src/screens/stake/redelegate/index.tsx, packages/mobile/src/screens/stake/undelegate/index.tsx, packages/mobile/src/screens/stake/validator-details/delegated-card.tsx, packages/mobile/src/screens/stake/validator-details/validator-details-card.tsx
=> chore: wallet UI fixes

packages/fetch-extension/src/components-v2/form/coin-input.tsx, packages/fetch-extension/src/components-v2/line-graph/index.tsx, packages/fetch-extension/src/components-v2/line-graph/line-graph.tsx, packages/fetch-extension/src/pages-new/asset-view/index.tsx, packages/fetch-extension/src/pages-new/portfolio/stats/index.tsx, packages/fetch-extension/src/pages-new/stake/dashboard/index.tsx, packages/fetch-extension/src/utils/format.ts, packages/mobile/src/screens/portfolio/token-detail/index.tsx
=> fix: balance NaN, Max CTA crash, Market price on token detail

packages/fetch-extension/src/pages-new/activity/activity-details/detail-row.tsx, packages/fetch-extension/src/pages-new/activity/activity-details/detail-rows.tsx, packages/fetch-extension/src/pages-new/activity/activity-details/index.tsx, packages/fetch-extension/src/pages-new/activity/activity-details/style.module.scss, packages/fetch-extension/src/pages-new/activity/gov-proposals/activity-row.tsx, packages/fetch-extension/src/pages-new/axelar-bridge/axelar-bridge-evm/send-token.tsx, packages/fetch-extension/src/pages/axelar-bridge/axelar-bridge-evm/send-token.tsx, packages/fetch-extension/src/utils/format.ts, packages/mobile/src/screens/activity/activity-details/details-rows.tsx, packages/mobile/src/screens/activity/activity-details/index.tsx, packages/mobile/src/screens/activity/gov-proposals/activity-row.tsx, packages/mobile/src/utils/format/format.tsx
=> Activity feature improvement

packages/fetch-extension/src/components-v2/form/memo-input.tsx, packages/fetch-extension/src/pages-new/activity/activity-details/detail-row.tsx, packages/fetch-extension/src/pages-new/activity/activity-details/style.module.scss, packages/fetch-extension/src/pages-new/send/send-phase-2.tsx, packages/fetch-extension/src/pages-new/sign/details-tab.module.scss, packages/popup/src/index.ts
1. UI of the wallet extension breaks, and the footer section appears distorted
2. Memo text going outside of the input box
=> chore: Ext UI improvements

packages/fetch-extension/src/config.ts, packages/fetch-extension/src/pages-new/more/index.tsx, packages/fetch-extension/src/pages-new/more/proposals/index.tsx, packages/fetch-extension/src/utils/index.ts
=> chore: disabled eridanus network and wallet guide link update
